spring:
  application:
    name: clubing

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: ${SPRING_PROFILES_INCLUDE:secret}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379        # Redisson, RedisTemplate 등에 사용됨

  cache:
    type: redis       # Spring Cache에서 Redis 사용 선언
    redis:
      host: localhost
      port: 6379      # CacheManager가 Redis에 연결할 때 사용

management:
  endpoints:
    web:
      exposure:
        include: "*"

