spring:
  application:
    name: clubing

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: ${SPRING_PROFILES_INCLUDE:secret}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

#  cache:
#    type: redis
#    data:
#      redis:
#        host: localhost
#        port: 6379
