spring:
  application:
    name: clubing

  profiles:
    active: local       # ?? ?? ?? ???
    include: secret     # ?? ??? ?? ??

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
